version: '3'
services:
  app:
    container_name: docker_group1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - test-network
    volumes:
      - test-vol:/app

volumes:
  test-vol:

networks:
  test-network: